export const INDUSTRIES = [
  "Law Firm",
  "Construction",
  "Food",
  "Car / Automotive",
  "Marketing",
  "School / Education",
  "Travel / Tourism",
  "Cafe / Restaurant",
  "Healthcare",
  "Government",
  "Restaurant",
  "Resort / Hospitality",
  "Finance",
  "Technology",
  "Retail",
  "Manufacturing",
  "Other",
];
